//------------------------------------------------------------------------------
// This file was generated by Localization task for Android
//------------------------------------------------------------------------------

namespace IndiaRose
{
	using IndiaRose.Droid;
	using Android.Content;
	
	public sealed class LocalizedStrings
	{
		private static Context _ctx;
		private LocalizedStrings()
		{
		}
		public static string Menu_About
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Menu_About);
			}
		}
		public static string Menu_Collection
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Menu_Collection);
			}
		}
		public static string Menu_Contact
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Menu_Contact);
			}
		}
		public static string Menu_Help
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Menu_Help);
			}
		}
		public static string Menu_Settings
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Menu_Settings);
			}
		}
		public static string Settings_BottomColorButton
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Settings_BottomColorButton);
			}
		}
		public static string Settings_EnableReinforcer
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Settings_EnableReinforcer);
			}
		}
		public static string Settings_FontFamilyLabel
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Settings_FontFamilyLabel);
			}
		}
		public static string Settings_FontSizeLabel
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Settings_FontSizeLabel);
			}
		}
		public static string Settings_IndiagramBottomPreviewText
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Settings_IndiagramBottomPreviewText);
			}
		}
		public static string Settings_IndiagramSizeLabel
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Settings_IndiagramSizeLabel);
			}
		}
		public static string Settings_IndiagramTopPreviewText
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Settings_IndiagramTopPreviewText);
			}
		}
		public static string Settings_ReinforcerColorLabel
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Settings_ReinforcerColorLabel);
			}
		}
		public static string Settings_TextColorLabel
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Settings_TextColorLabel);
			}
		}
		public static string Settings_TopColorButton
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Settings_TopColorButton);
			}
		}
		public static void Initialize(Context ctx)
		{
			LocalizedStrings._ctx = ctx;
		}
	}
}
