//------------------------------------------------------------------------------
// This file was generated by Localization task for Android
//------------------------------------------------------------------------------

namespace IndiaRose
{
	using IndiaRose.Droid;
	using Android.Content;
	
	public sealed class LocalizedStrings
	{
		private static Context _ctx;
		private LocalizedStrings()
		{
		}
		public static string Menu_About
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Menu_About);
			}
		}
		public static string Menu_Collection
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Menu_Collection);
			}
		}
		public static string Menu_Contact
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Menu_Contact);
			}
		}
		public static string Menu_Help
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Menu_Help);
			}
		}
		public static string Menu_Settings
		{
			get
			{
				return LocalizedStrings._ctx.GetString(Resource.String.Menu_Settings);
			}
		}
		public static void Initialize(Context ctx)
		{
			LocalizedStrings._ctx = ctx;
		}
	}
}
