//------------------------------------------------------------------------------
// This file was generated by Localization task for Android
//------------------------------------------------------------------------------

namespace IndiaRose
{
	using IndiaRose.Droid;
	using Android.Content;
	
	public class LocalizationService : ILocalizationService
	{
		private Context _ctx;
		public LocalizationService(Context ctx)
		{
			this._ctx = ctx;
		}
		public virtual string Get(EnumStrings key)
		{
			if ((key == EnumStrings.Menu_About))
			{
				return this._ctx.GetString(Resource.String.Menu_About);
			}
			if ((key == EnumStrings.Menu_Collection))
			{
				return this._ctx.GetString(Resource.String.Menu_Collection);
			}
			if ((key == EnumStrings.Menu_Contact))
			{
				return this._ctx.GetString(Resource.String.Menu_Contact);
			}
			if ((key == EnumStrings.Menu_Help))
			{
				return this._ctx.GetString(Resource.String.Menu_Help);
			}
			if ((key == EnumStrings.Menu_Settings))
			{
				return this._ctx.GetString(Resource.String.Menu_Settings);
			}
			throw new System.ArgumentOutOfRangeException();
		}
	}
}
